apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bonipoddd2
  name: bonipoddd2
spec:
  containers:
  - image: dockerashu/ckad:v2
    name: bonipoddd
    env:
    - name: color  # key/variable from env in dockerfile
      valueFrom:
       configMapKeyRef:
        name: shreyacm1  # name of config map
        key: y  # name of key that stores value in configmap
    - name: color1
      valueFrom:
       configMapKeyRef:
        name: shreyacm1
        key: y1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
