apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pengupod
  name: pengupod
spec:
  containers:
  - image: nginx
    name: pengupod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
