apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # is important if you want your application can get the traffic from service
   x: hello # label always should be in key: value pair and must be unique
  name: pod1 # must be unique
spec:
  containers:
  - image: shreya2001/alpine:entry
    name: pod1
    ports:
    command: ["/bin/sh","-c","cal"]

