apiVersion: v1
kind: Service
metadata:
  name: myservice1
spec:
 ports:
  - name: mysvcport
    port: 1122 # this is must and is the port of service ip
    targetPort: 80 #this must match the port number of the POD
    protocol: TCP
 selector:
  x: hello # this label must match the POD label where we want to forward the traffic
 type: NodePort
